apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-master-node-svc
  labels:
    type: master-node
spec:
  type: NodePort
  ports:
  - port: 5100
    nodePort: 31111
  selector:
    type: master-node
